config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'listings#index'

  resources :listings do
    collection { post :search, to: 'listings#index' }
  end

end

app/models/listing.rb
class Listing < ActiveRecord::Base
	has_many :manufacturers
	belongs_to :user

end

app/models/manufacturer.rb
class Manufacturer < ActiveRecord::Base



end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :listings

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController

	before_action :authenticate_user!, :only => [:new, :create]


	def index
		
		@search = Listing.search(params[:q])
 	 	@listings = @search.result.order("year").page(params[:page]).per(10)
	end

	def new
		@listing = Listing.new
	end


	def create
    	current_user.listings.create(listing_params)
    	redirect_to root_path
  	end

  private

	def listing_params
	    params.require(:listing).permit(:year, :make, :model, :submodel, :description, :wheelsize, :mileage)
	end


end

app/controllers/manufacturers_controller.rb
class ManufacturersController < ApplicationController

	def index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/manufacturers_helper.rb
module ManufacturersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EAB - Electric Auto Bureau</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-inverse" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
       <%= link_to 'EAB', root_path, :class => 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'New Listing', new_listing_path %></li>
        <% if user_signed_in? %>
        <li><%= link_to 'Sign out', destroy_user_session_path, :method => :delete %></li>
        <% else %>
        <li><%= link_to 'Sign in', new_user_session_path %></li>
        <li><%= link_to 'Sign up', new_user_registration_path %></li>
        <% end %>
        <li><a href="#">Link</a></li><li><a href="#">Help</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<% if notice.present? %>
  <p class="alert alert-info"><%= notice %></p>
<% end %>
<% if alert.present? %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

<%= yield %>
</body>
</html>

app/views/listings/index.html.erb
<div class="booyah-box col-xs-2 col-xs-offset-1">
	<%= search_form_for @search, url: search_listings_path, method: :post do |f| %>
		<div class="field">
    		
			<%= f.label :make_cont, "Make" %>
			<%= f.collection_select(:make_cont, Manufacturer.all, :name, :name) %>
			<br /><br />
			<%= f.label :model_cont, "Model" %>
			<%= f.text_field :model_cont %>
			<%= f.label :mileage_gteq, "Mileage Min" %>
			<%= f.text_field :mileage_gteq %>
			<%= f.label :mileage_lteq, "Mileage Max" %>
			<%= f.text_field :mileage_lteq %>
		</div><br />
		<div class="actions"><%= f.submit "Search" %></div>
</div>
<% end %>
<div class="col-xs-8">
<% @listings.each do |l| %>
	<div class="booyah-box">
		<h2><%= l.year %> <%= l.make %> <%= l.model %> <%= l.submodel %></h2><br />
		<ul>
			<li><%= l.mileage %></li>
			<li><%= l.wheelsize %></li>
			<li><%= l.description %></li>
		</ul>
		<br /><br />User Email
		 <% if l.user.present? %>
   		   <small><%= l.user.email %></small>
    	 <% end %>
	</div>

<% end %>
</div>

<div class="row">
	<div class="paginate col-md-3 col-xs-3 col-md-offset-8 col-xs-offset-8">
		<h4><span class="prev disabled"><%= raw(t 'views.pagination.previous') %></span>
				<%= paginate @listings %></h4>
		</div>
</div>

app/views/listings/new.html.erb
<h1>New Listing</h1>

<div class="booyah-box col-xs-10 col-xs-offset-1">
  <h1>Your Electic Car Details</h1>
  <%= simple_form_for @listing do |f| %>
    <%= f.input :year %>
    <%= f.input :make %>
    <%= f.input :model %>
    <%= f.input :submodel %>
    <%= f.input :description %>
    <%= f.input :wheelsize %>
    <%= f.input :mileage %>
     <br />
      <%= f.submit 'Create', :class => 'btn btn-primary' %>
  <% end %>
</div>